name: "gs-sds-mvdream"
tag: "${rmspace:${system.prompt_processor.prompt},_}"
exp_root_dir: "outputs"
seed: 0

data_type: "mvdream-random-multiview-camera-datamodule"
data:
  batch_size: 4
  n_view: 4
  # 0-4999: 64x64, >=5000: 256x256
  width: 512
  height: 512
  camera_distance_range: [0.8, 1.0] # relative
  fovy_range: [15, 60]
  elevation_range: [0, 30]
  camera_perturb: 0.
  center_perturb: 0.
  up_perturb: 0.
  n_val_views: 4
  eval_camera_distance: 3.0
  eval_fovy_deg: 40.
  rays_d_normalize: false

system_type: "gaussiandreamer-mvdream-system"
system:
  geometry_type: "gaussiandreamer-base"
  geometry:
    position_lr: 0.00005
    scale_lr: 0.005
    feature_lr: 0.01
    opacity_lr: 0.01
    rotation_lr: 0.001
    pred_normal: false
    normal_lr: 0.005

    densification_interval: 100
    prune_interval: 100
    densify_from_iter: 300
    densify_until_iter: 900
    prune_from_iter: 300
    prune_until_iter: 900
    opacity_reset_interval: 100000

    densify_grad_threshold: 0.0002
    min_opac_prune: 0.05
    split_thresh: 0.01
    radii2d_thresh: 1000

    opacity_init: 0.1
    pc_init_radius: 0.6

  renderer_type: "gaussiandreamer-rasterizer"
  renderer:
    debug: false
    invert_bg_prob: 0.5

  material_type: "no-material" # unused
  material:
    n_output_dims: 0

  background_type: "gaussiandreamer-background"
  background:
    color_activation: sigmoid
    random_aug: true
    share_aug_bg: true
    random_aug_prob: 0.95

  prompt_processor_type: "stable-diffusion-prompt-processor"
  prompt_processor:
    pretrained_model_name_or_path: "stabilityai/stable-diffusion-2-1-base"
    prompt: ???
    negative_prompt: "ugly, bad anatomy, blurry, pixelated obscure, unnatural colors, poor lighting, dull, and unclear, cropped, lowres, low quality, artifacts, duplicate, morbid, mutilated, poorly drawn face, deformed, dehydrated, bad proportions, unfocused"

  guidance_type: "mvdream-multiview-diffusion-guidance"
  guidance:
    model_name: "sd-v2.1-base-4view"
    ckpt_path: null # path to a pre-downloaded checkpoint file (null for loading from URL)
    guidance_scale: 50.0
    min_step_percent: 0.02  # (start_iter, start_val, end_val, end_iter)
    max_step_percent: [500, 0.98, 0.5, 501]
    recon_loss: true
    recon_std_rescale: 0.5

  exporter_type: "gaussiandreamer-mesh-exporter"

  loggers:
    wandb:
      enable: false
      project: 'threestudio'
      name: None

  loss:
    lambda_sds: 1.
    lambda_sparsity: 0.
    lambda_position: 0.
    lambda_opacity: 0.
    lambda_scales: 0.
    lambda_tv_loss: 0.0
    lambda_depth_tv_loss: 0.

trainer:
  max_steps: 1200
  log_every_n_steps: 1
  num_sanity_val_steps: 0
  val_check_interval: 100
  enable_progress_bar: true
  precision: 32-true

checkpoint:
  save_last: true # save at each validation time
  save_top_k: -1
  every_n_train_steps: ${trainer.max_steps}
